# Learn TSA Basics

In [1]:
# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

In [2]:
# Import the created database
from Descriptive import Descriptive

In [3]:
Obj = Descriptive()

In [4]:
# import TSA library and assign input variables
from nsepy import get_history as gh
import datetime as dt
import yfinance as yf
stock_symbol = "RELIANCE.NS"
start = dt.datetime(2021,6,1)
end = dt.datetime(2022,1,5)
Stock_data = yf.download(stock_symbol, start=start, end=end)

[*********************100%***********************]  1 of 1 completed

In [5]:
Stock_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 150 entries, 2021-06-01 to 2022-01-04
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (Close, RELIANCE.NS)   150 non-null    float64
 1   (High, RELIANCE.NS)    150 non-null    float64
 2   (Low, RELIANCE.NS)     150 non-null    float64
 3   (Open, RELIANCE.NS)    150 non-null    float64
 4   (Volume, RELIANCE.NS)  150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 7.0 KB

In [6]:
Stock_data

Price             Close         High          Low         Open      Volume
Ticker      RELIANCE.NS  RELIANCE.NS  RELIANCE.NS  RELIANCE.NS RELIANCE.NS
Date
2021-06-01   978.920898   993.860389   968.810735   977.611971    28013832
2021-06-02   993.521912   997.245502   973.549903   973.549903    24630162
2021-06-03   997.313171  1015.524921   991.197481  1002.435884    23974257
2021-06-04   988.669983  1000.382342   985.849055   999.637624    14468646
2021-06-07  1005.324524  1011.914169   986.187547   993.860425    16336573
...                 ...          ...          ...          ...         ...
2021-12-29  1088.135376  1095.608521  1078.895776  1082.926817    15425312
2021-12-30  1068.478760  1089.245071  1062.364390  1087.003127    29333171
2021-12-31  1072.577515  1079.710905  1068.886227  1074.774173     9477290
2022-01-03  1088.746704  1090.603729  1070.494166  1071.150911     5421611
2022-01-04  1113.317505  1114.630996  1088.814624  1094.204441    10847728

[150 rows x 5 columns]

In [7]:
Low = Stock_data["Low"]

In [8]:
Dataset = Stock_data
Quan,Qual = Obj.segreQuanQual(Dataset)

The Quantitative Data: [('Close', 'RELIANCE.NS'), ('High', 'RELIANCE.NS'), ('Low', 'RELIANCE.NS'), ('Open', 'RELIANCE.NS'), ('Volume', 'RELIANCE.NS')]
The Qualtitative Data []

In [9]:
Des_data = Obj.descriptive_Analysis(Dataset,Quan)
Des_data

,"(Close, RELIANCE.NS)","(High, RELIANCE.NS)","(Low, RELIANCE.NS)","(Open, RELIANCE.NS)","(Volume, RELIANCE.NS)"
Null_count,0,0,0,0,0
NonNull_count,150,150,150,150,150
Total_Count,150,150,150,150,150
Mean,1057.407558,1069.158087,1047.01047,1059.003782,14584981.813333
Median,1072.113281,1084.908157,1062.930499,1073.891059,12087939.0
Mode,944.786804,932.105071,913.195727,930.293307,1705656
Std,85.69408,87.654419,83.742203,86.078624,9640997.620994
Min,921.823853,932.105071,913.195727,930.293307,1705656.0
Q1:25%,979.032455,989.897483,968.116845,975.922032,9784558.0
Q2:50%,1072.113281,1084.908157,1062.930499,1073.891059,12087939.0
Q3:75%,1124.510223,1132.175924,1111.828537,1124.878287,15759452.75
Q4:100%,1237.303711,1246.13563,1226.501675,1242.240558,91461975.0
IQR,145.477768,142.278442,143.711691,148.956255,5974894.75
1.5Rule,218.216652,213.417663,215.567537,223.434382,8962342.125
Lesser,760.815804,776.47982,752.549308,752.48765,822215.875
Greater,1342.726875,1345.593587,1327.396074,1348.312669,24721794.875

In [10]:
Des_data["Low, RELIANCE.NS"]

KeyError: 'Low, RELIANCE.NS'

In [ ]:
import numpy as np

In [ ]:
np.percentile(Dataset["Low"], 99)

In [ ]:
np.percentile(Dataset["High"], 99)